-- MySQL Script generated by MySQL Workbench
-- Mon Oct  5 20:57:14 2026
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `mydb` ;

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `mydb` DEFAULT CHARACTER SET utf8 ;
USE `mydb` ;

-- -----------------------------------------------------
-- Table `mydb`.`VENDEDOR`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`VENDEDOR` ;

CREATE TABLE IF NOT EXISTS `mydb`.`VENDEDOR` (
  `ID_VENDEDOR` INT NOT NULL,
  `NOME_VENDEDOR` VARCHAR(100) NULL,
  `TEL_VENDEDOR` VARCHAR(20) NULL,
  PRIMARY KEY (`ID_VENDEDOR`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`CLIENTE`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`CLIENTE` ;

CREATE TABLE IF NOT EXISTS `mydb`.`CLIENTE` (
  `ID_CLIENTE` INT NOT NULL,
  `NOME_CLIENTE` VARCHAR(45) NOT NULL,
  `TEL_CLIENTE` VARCHAR(20) NULL,
  PRIMARY KEY (`ID_CLIENTE`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`VENDEDOR_CLIENTE`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`VENDEDOR_CLIENTE` ;

CREATE TABLE IF NOT EXISTS `mydb`.`VENDEDOR_CLIENTE` (
  `VENDEDOR_ID_VENDEDOR` INT NOT NULL,
  `CLIENTE_ID_CLIENTE` INT NOT NULL,
  `DATA_HORA_ATENDIMENTO` DATETIME(3) NOT NULL,
  PRIMARY KEY (`VENDEDOR_ID_VENDEDOR`, `CLIENTE_ID_CLIENTE`, `DATA_HORA_ATENDIMENTO`),
  INDEX `fk_VENDEDOR_has_CLIENTE_CLIENTE1_idx` (`CLIENTE_ID_CLIENTE` ASC) VISIBLE,
  INDEX `fk_VENDEDOR_has_CLIENTE_VENDEDOR_idx` (`VENDEDOR_ID_VENDEDOR` ASC) VISIBLE,
  CONSTRAINT `fk_VENDEDOR_has_CLIENTE_VENDEDOR`
    FOREIGN KEY (`VENDEDOR_ID_VENDEDOR`)
    REFERENCES `mydb`.`VENDEDOR` (`ID_VENDEDOR`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_VENDEDOR_has_CLIENTE_CLIENTE1`
    FOREIGN KEY (`CLIENTE_ID_CLIENTE`)
    REFERENCES `mydb`.`CLIENTE` (`ID_CLIENTE`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`PEDIDO`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`PEDIDO` ;

CREATE TABLE IF NOT EXISTS `mydb`.`PEDIDO` (
  `ID_PEDIDO` INT NOT NULL,
  `NUM_PEDIDO` INT NOT NULL,
  `DATA_PEDIDO` DATETIME NOT NULL,
  `VENDEDOR_ID_VENDEDOR` INT NOT NULL,
  `CLIENTE_ID_CLIENTE` INT NOT NULL,
  PRIMARY KEY (`ID_PEDIDO`),
  INDEX `fk_PEDIDO_VENDEDOR1_idx` (`VENDEDOR_ID_VENDEDOR` ASC) VISIBLE,
  INDEX `fk_PEDIDO_CLIENTE1_idx` (`CLIENTE_ID_CLIENTE` ASC) VISIBLE,
  CONSTRAINT `fk_PEDIDO_VENDEDOR1`
    FOREIGN KEY (`VENDEDOR_ID_VENDEDOR`)
    REFERENCES `mydb`.`VENDEDOR` (`ID_VENDEDOR`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_PEDIDO_CLIENTE1`
    FOREIGN KEY (`CLIENTE_ID_CLIENTE`)
    REFERENCES `mydb`.`CLIENTE` (`ID_CLIENTE`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`PRODUTO`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`PRODUTO` ;

CREATE TABLE IF NOT EXISTS `mydb`.`PRODUTO` (
  `ID_PRODUTO` INT NOT NULL,
  `NOME_PRODUTO` VARCHAR(45) NOT NULL,
  `DESCRICAO_PRODUTO` VARCHAR(200) NOT NULL,
  `PART_NUMBER_PRODUTO` INT NULL,
  `PU_PRODUTO` DECIMAL(10,2) NOT NULL,
  `QUANT_PRODUTO` INT NOT NULL,
  `UNIDADE_FORNECIMENTO_PRODUTO` VARCHAR(100) NOT NULL,
  `DATA_FABRIC_PRODUTO` DATETIME NOT NULL,
  `DATA_VALIDADE_PRODUTO` DATE NOT NULL,
  `COD_BARRA_PRODUTO` VARCHAR(18) NOT NULL,
  PRIMARY KEY (`ID_PRODUTO`),
  UNIQUE INDEX `COD_BARRA_UNIQUE` (`COD_BARRA_PRODUTO` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`ITEM_PEDIDO`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`ITEM_PEDIDO` ;

CREATE TABLE IF NOT EXISTS `mydb`.`ITEM_PEDIDO` (
  `PEDIDO_ID_PEDIDO` INT NOT NULL,
  `PRODUTO_ID_PRODUTO` INT NOT NULL,
  `QUANT_ITEM_PEDIDO` INT NULL,
  PRIMARY KEY (`PEDIDO_ID_PEDIDO`, `PRODUTO_ID_PRODUTO`),
  INDEX `fk_PEDIDO_has_PRODUTO_PRODUTO1_idx` (`PRODUTO_ID_PRODUTO` ASC) VISIBLE,
  INDEX `fk_PEDIDO_has_PRODUTO_PEDIDO1_idx` (`PEDIDO_ID_PEDIDO` ASC) VISIBLE,
  CONSTRAINT `fk_PEDIDO_has_PRODUTO_PEDIDO1`
    FOREIGN KEY (`PEDIDO_ID_PEDIDO`)
    REFERENCES `mydb`.`PEDIDO` (`ID_PEDIDO`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_PEDIDO_has_PRODUTO_PRODUTO1`
    FOREIGN KEY (`PRODUTO_ID_PRODUTO`)
    REFERENCES `mydb`.`PRODUTO` (`ID_PRODUTO`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;

-- VENDEDORES
INSERT INTO vendedor (id_vendedor, nome_vendedor, tel_vendedor) VALUES
(1, 'Maria Soares', null),
(2, 'Bruna Almeida', null),
(3, 'Rafael Santos', '11914406370'),
(4, 'Carlos Soares', '11945992856'),
(5, 'João Ribeiro', '11991706625'),
(6, 'Luiz Santos', '11993194719'),
(7, 'Letícia Ribeiro', '11920941336'),
(8, 'Lucas Martins', '11990201620'),
(9, 'Lucas Gomes', '11925034927'),
(10, 'Rafael Silva', '11938384292'),
(11, 'Carlos Rodrigues', '11991631315'),
(12, 'Pedro Martins', '11942218739'),
(13, 'Ana Alves', '11975111096'),
(14, 'Bruna Vieira', '11967702404'),
(15, 'Juliana Santos', '11997723299'),
(16, 'Camila Oliveira', '11926697534'),
(17, 'Bruna Alves', '11993045513'),
(18, 'Bruna Ferreira', '11992711003'),
(19, 'João Barbosa', '11929008656'),
(20, 'Carlos Silva', '11966097816'),
(21, 'Maria Gomes', '11923529444'),
(22, 'Gustavo Rodrigues', '11943588555'),
(23, 'Marcos Santos', '11990886219'),
(24, 'Ana Santos', '11979371067'),
(25, 'Ana Carvalho', '11987631104'),
(26, 'Juliana Costa', '11962388047'),
(27, 'Mariana Costa', '11957418468'),
(28, 'Letícia Silva', '11984252631'),
(29, 'Pedro Ribeiro', '11933994326'),
(30, 'Rafael Almeida', '11926639535'),
(31, 'Marcos Souza', '11942918844'),
(32, 'Larissa Alves', '11963004381'),
(33, 'Camila Barbosa', '11931393856'),
(34, 'Marcos Costa', '11910609315'),
(35, 'Letícia Gomes', '11935515082'),
(36, 'Mariana Martins', '11938302251'),
(37, 'Amanda Lima', '11922037996'),
(38, 'João Silva', '11931627581'),
(39, 'Larissa Martins', '11991738711'),
(40, 'Pedro Oliveira', '11939524410'),
(41, 'Letícia Souza', '11987019623'),
(42, 'Larissa Lima', '11928096350'),
(43, 'Marcos Gomes', '11910185906'),
(44, 'Juliana Martins', '11924519967'),
(45, 'Vanessa Ferreira', '11972688746'),
(46, 'Diego Lopes', '11956094628'),
(47, 'Marcos Souza', '11941655189'),
(48, 'Maria Ferreira', '11962319082'),
(49, 'Diego Silva', '11931301050'),
(50, 'Gabriel Almeida', '11967202302'),
(51, 'Ana Vieira', '11954157833'),
(52, 'Diego Oliveira', '11972986421'),
(53, 'Marcos Alves', '11958611843'),
(54, 'Luiz Lima', '11969018441'),
(55, 'Marcos Fernandes', '11940176426'),
(56, 'Mariana Alves', '11928331189'),
(57, 'Gabriel Carvalho', '11943015409'),
(58, 'Camila Lima', '11978018742'),
(59, 'Letícia Alves', '11963242095'),
(60, 'Mariana Fernandes', '11945037168'),
(61, 'Marcos Silva', '11922579124'),
(62, 'Pedro Soares', '11965581143'),
(63, 'Lucas Oliveira', '11942008316'),
(64, 'Diego Barbosa', '11913919421'),
(65, 'Gustavo Barbosa', '11998522049'),
(66, 'Vanessa Souza', '11952479021'),
(67, 'Letícia Santos', '11989445108'),
(68, 'Luiz Gomes', '11920392305'),
(69, 'Mariana Costa', '11973412586'),
(70, 'Gabriel Ferreira', '11969316520'),
(71, 'Diego Rodrigues', '11956637418'),
(72, 'Marcos Ribeiro', '11921319407'),
(73, 'Lucas Rodrigues', '11925695022'),
(74, 'Pedro Ribeiro', '11981014523'),
(75, 'Camila Barbosa', '11939108422'),
(76, 'João Souza', '11972101955'),
(77, 'Ana Lopes', '11993208754'),
(78, 'Larissa Rodrigues', '11952416390'),
(79, 'Luiz Barbosa', '11934211105'),
(80, 'Gabriel Soares', '11968843912'),
(81, 'Maria Ribeiro', '11998317420'),
(82, 'Diego Silva', '11929312048'),
(83, 'Mariana Lopes', '11964121950'),
(84, 'Carlos Almeida', '11993215582'),
(85, 'Marcos Lopes', '11949102431'),
(86, 'Juliana Pereira', '11933017596'),
(87, 'Diego Pereira', '11982143588'),
(88, 'Letícia Costa', '11942106399'),
(89, 'Vanessa Alves', '11956102488'),
(90, 'Pedro Santos', '11939218520'),
(91, 'Amanda Vieira', '11963214820'),
(92, 'Rafael Barbosa', '11925317482'),
(93, 'Luiz Fernandes', '11974103629'),
(94, 'João Almeida', '11962145533'),
(95, 'Camila Costa', '11992147481'),
(96, 'Maria Fernandes', '11936102577'),
(97, 'Mariana Lima', '11942153699'),
(98, 'Juliana Lopes', '11931047485'),
(99, 'Lucas Alves', '11974102239'),
(100, 'Gustavo Vieira', '11965214785');

-- CLIENTES
INSERT INTO cliente (id_cliente, nome_cliente, tel_cliente) VALUES
(1, 'Lucas Oliveira', '(11) 98576-5809'),
(2, 'Fernanda Gomes', '(11) 99730-9981'),
(3, 'Fernanda Santos', '(11) 97891-7573'),
(4, 'Roberto Pereira', '(11) 99929-6128'),
(5, 'Amanda Costa', '(11) 98272-7495'),
(6, 'Gustavo Almeida', '(11) 97322-3568'),
(7, 'Larissa Ribeiro', '(11) 98938-9579'),
(8, 'Diana Costa', '(11) 98294-4157'),
(9, 'Patricia Vieira', '(11) 99323-8780'),
(10, 'Diana Lima', '(11) 99537-8688'),
(11, 'Beatriz Pereira', '(11) 98193-9907'),
(12, 'Roberto Rodrigues', '(11) 98508-5408'),
(13, 'Mariana Ferreira', '(11) 97073-2465'),
(14, 'Gabriel Souza', '(11) 97614-6151'),
(15, 'Lucas Ribeiro', '(11) 97933-9808'),
(16, 'Roberto Martins', '(11) 98792-7520'),
(17, 'Lucas Alves', '(11) 97440-3729'),
(18, 'Pedro Alves', '(11) 97963-7477'),
(19, 'Diana Lima', '(11) 98683-7858'),
(20, 'Amanda Alves', '(11) 97684-1560'),
(21, 'Bruno Ribeiro', '(11) 97329-2152'),
(22, 'Gustavo Costa', '(11) 99913-6749'),
(23, 'Rodrigo Ferreira', '(11) 99238-1422'),
(24, 'Camila Souza', '(11) 98457-3162'),
(25, 'Thiago Martins', '(11) 97124-8899'),
(26, 'Julia Almeida', '(11) 99632-4411'),
(27, 'Pedro Gomes', '(11) 98115-7744'),
(28, 'Beatriz Silva', '(11) 97552-3366'),
(29, 'Carlos Rodrigues', '(11) 99441-2255'),
(30, 'Eduardo Costa', '(11) 98332-1188'),
(31, 'Ana Barbosa', '(11) 97223-9977'),
(32, 'Larissa Vieira', '(11) 99884-6633'),
(33, 'Mariana Lopes', '(11) 98775-5522'),
(34, 'Rodrigo Soares', '(11) 97661-4411'),
(35, 'Camila Fernandes', '(11) 99552-8899'),
(36, 'Patricia Santos', '(11) 98443-7766'),
(37, 'Gustavo Oliveira', '(11) 97334-6655'),
(38, 'Bruno Souza', '(11) 99225-5544'),
(39, 'Ana Rodrigues', '(11) 98116-4433'),
(40, 'Carlos Ferreira', '(11) 97007-3322'),
(41, 'Diana Alves', '(11) 99991-2211'),
(42, 'Eduardo Pereira', '(11) 98882-1100'),
(43, 'Fernanda Lima', '(11) 97773-9900'),
(44, 'Gabriel Gomes', '(11) 96664-8877'),
(45, 'Amanda Costa', '(11) 95555-7766'),
(46, 'Lucas Ribeiro', '(11) 94446-6655'),
(47, 'Julia Martins', '(11) 93337-5544'),
(48, 'Roberto Carvalho', '(11) 92228-4433'),
(49, 'Mariana Almeida', '(11) 91119-3322'),
(50, 'Rodrigo Lopes', '(11) 98765-4321'),
(51, 'Camila Soares', '(11) 97654-3210'),
(52, 'Patricia Fernandes', '(11) 96543-2109'),
(53, 'Gustavo Vieira', '(11) 95432-1098'),
(54, 'Beatriz Barbosa', '(11) 94321-0987'),
(55, 'Pedro Silva', '(11) 93210-9876'),
(56, 'Larissa Santos', '(11) 92109-8765'),
(57, 'Thiago Oliveira', '(11) 91098-7654'),
(58, 'Ana Souza', '(11) 99876-5432'),
(59, 'Bruno Rodrigues', '(11) 98765-4321'),
(60, 'Carlos Ferreira', '(11) 97654-3210'),
(61, 'Diana Alves', '(11) 96543-2109'),
(62, 'Eduardo Pereira', '(11) 95432-1098'),
(63, 'Fernanda Lima', '(11) 94321-0987'),
(64, 'Gabriel Gomes', '(11) 93210-9876'),
(65, 'Amanda Costa', '(11) 92109-8765'),
(66, 'Lucas Ribeiro', '(11) 91098-7654'),
(67, 'Julia Martins', '(11) 99887-6655'),
(68, 'Roberto Carvalho', '(11) 98776-5544'),
(69, 'Mariana Almeida', '(11) 97665-4433'),
(70, 'Rodrigo Lopes', '(11) 96554-3322'),
(71, 'Camila Soares', '(11) 95443-2211'),
(72, 'Patricia Fernandes', '(11) 94332-1100'),
(73, 'Gustavo Vieira', '(11) 93221-0099'),
(74, 'Beatriz Barbosa', '(11) 92110-9988'),
(75, 'Pedro Silva', '(11) 91009-8877'),
(76, 'Larissa Santos', '(11) 99999-8888'),
(77, 'Thiago Oliveira', '(11) 98888-7777'),
(78, 'Ana Souza', '(11) 97777-6666'),
(79, 'Bruno Rodrigues', '(11) 96666-5555'),
(80, 'Carlos Ferreira', '(11) 95555-4444'),
(81, 'Diana Alves', '(11) 94444-3333'),
(82, 'Eduardo Pereira', '(11) 93333-2222'),
(83, 'Fernanda Lima', '(11) 92222-1111'),
(84, 'Gabriel Gomes', '(11) 91111-0000'),
(85, 'Amanda Costa', '(11) 99888-7777'),
(86, 'Lucas Ribeiro', '(11) 98777-6666'),
(87, 'Julia Martins', '(11) 97666-5555'),
(88, 'Roberto Carvalho', '(11) 96555-4444'),
(89, 'Mariana Almeida', '(11) 95444-3333'),
(90, 'Rodrigo Lopes', '(11) 94333-2222'),
(91, 'Camila Soares', '(11) 93222-1111'),
(92, 'Patricia Fernandes', '(11) 92111-0000'),
(93, 'Gustavo Vieira', '(11) 91000-9999'),
(94, 'Beatriz Barbosa', '(11) 99990-8888'),
(95, 'Pedro Silva', '(11) 98880-7777'),
(96, 'Larissa Santos', '(11) 97770-6666'),
(97, 'Thiago Oliveira', '(11) 96660-5555'),
(98, 'Ana Souza', '(11) 95550-4444'),
(99, 'Bruno Rodrigues', '(11) 94440-3333'),
(100, 'Carlos Ferreira', '(11) 93330-2222');

-- VENDEDOR-CLIENTE
INSERT INTO VENDEDOR_CLIENTE (VENDEDOR_ID_VENDEDOR, CLIENTE_ID_CLIENTE, DATA_HORA_ATENDIMENTO) VALUES
(42, 87, '2026-01-15 09:30:00'), -- Par 42 e 87 (Ocorrência 1)
(12, 54, '2026-01-18 14:15:00'), -- Par 12 e 54 (Ocorrência 1)
(78, 23, '2026-01-22 11:05:00'), -- Par 78 e 23 (Ocorrência 1)
(33, 87, '2026-02-02 16:45:00'),
(95, 11, '2026-02-05 10:20:00'),
(42, 87, '2026-02-10 13:10:00'), -- Par 42 e 87 (Ocorrência 2)
(12, 54, '2026-02-14 15:35:00'), -- Par 12 e 54 (Ocorrência 2)
(61, 49, '2026-02-19 09:00:00'),
(18, 92, '2026-02-25 17:25:00'),
(78, 23, '2026-03-01 11:40:00'), -- Par 78 e 23 (Ocorrência 2)
(27, 73, '2026-03-05 14:50:00'),
(50, 15, '2026-03-12 10:15:00'),
(9, 88, '2026-03-19 16:10:00'),
(63, 41, '2026-03-24 12:30:00'),
(42, 87, '2026-03-29 08:55:00'), -- Par 42 e 87 (Ocorrência 3)
(36, 70, '2026-04-03 15:20:00'),
(14, 99, '2026-04-08 11:05:00'),
(80, 6, '2026-04-14 14:40:00'),
(78, 23, '2026-04-20 17:15:00'), -- Par 78 e 23 (Ocorrência 3)
(22, 81, '2026-04-25 09:45:00'),
(12, 54, '2026-05-02 13:30:00'), -- Par 12 e 54 (Ocorrência 3)
(42, 87, '2026-05-06 10:50:00'), -- Par 42 e 87 (Ocorrência 4)
(47, 68, '2026-05-11 16:00:00'),
(3, 29, '2026-05-17 11:15:00'),
(68, 77, '2026-05-22 14:25:00'),
(89, 43, '2026-05-28 09:10:00'),
(31, 90, '2026-06-02 15:35:00'),
(78, 23, '2026-06-08 12:00:00'), -- Par 78 e 23 (Ocorrência 4)
(58, 62, '2026-06-13 16:45:00'),
(19, 5, '2026-06-19 10:30:00'),
(83, 84, '2026-06-24 14:10:00'),
(12, 54, '2026-06-30 11:55:00'), -- Par 12 e 54 (Ocorrência 4)
(97, 71, '2026-07-04 15:20:00'),
(11, 48, '2026-07-09 09:35:00'),
(66, 93, '2026-07-15 13:40:00'),
(25, 14, '2026-07-21 16:50:00'),
(42, 87, '2026-07-26 10:15:00'), -- Par 42 e 87 (Ocorrência 5)
(52, 38, '2026-08-01 14:30:00'),
(6, 82, '2026-08-06 11:10:00'),
(88, 21, '2026-08-12 17:05:00'),
(34, 69, '2026-08-17 09:25:00'),
(12, 54, '2026-08-23 15:40:00'), -- Par 12 e 54 (Ocorrência 5)
(15, 50, '2026-08-28 13:15:00'),
(93, 8, '2026-09-02 10:00:00'),
(46, 75, '2026-09-08 16:20:00'),
(2, 33, '2026-09-13 11:45:00'),
(60, 60, '2026-09-19 14:50:00'),
(78, 23, '2026-09-24 09:15:00'), -- Par 78 e 23 (Ocorrência 5)
(29, 86, '2026-09-30 15:10:00'),
(70, 44, '2026-10-05 12:35:00'),
(13, 91, '2026-10-11 10:40:00'),
(99, 28, '2026-10-16 16:15:00'),
(42, 87, '2026-10-22 14:00:00'), -- Par 42 e 87 (Ocorrência 6)
(38, 79, '2026-10-27 11:25:00'),
(81, 7, '2026-11-02 09:50:00'),
(23, 53, '2026-11-07 15:30:00'),
(67, 36, '2026-11-13 13:05:00'),
(12, 54, '2026-11-18 10:20:00'), -- Par 12 e 54 (Ocorrência 6)
(92, 19, '2026-11-24 16:45:00'),
(41, 65, '2026-11-29 12:15:00'),
(76, 42, '2026-12-04 14:55:00'),
(4, 85, '2026-12-10 09:10:00'),
(51, 24, '2026-12-15 11:35:00'),
(78, 23, '2026-12-21 15:20:00'), -- Par 78 e 23 (Ocorrência 6)
(30, 10, '2026-12-27 16:40:00'),
(42, 87, '2026-12-30 10:00:00'), -- Par 42 e 87 (Ocorrência 7)
(17, 56, '2026-01-16 14:20:00'),
(65, 32, '2026-02-11 09:45:00'),
(94, 80, '2026-03-06 11:30:00'),
(28, 45, '2026-04-01 16:10:00'),
(12, 54, '2026-04-22 13:15:00'), -- Par 12 e 54 (Ocorrência 7)
(56, 13, '2026-05-14 10:05:00'),
(10, 83, '2026-06-05 15:40:00'),
(82, 37, '2026-06-26 11:20:00'),
(44, 76, '2026-07-17 14:50:00'),
(98, 22, '2026-08-08 09:30:00'),
(37, 59, '2026-08-29 16:00:00'),
(86, 2, '2026-09-19 12:15:00'),
(21, 67, '2026-10-10 10:45:00'),
(74, 95, '2026-10-31 15:25:00'),
(53, 16, '2026-11-21 11:10:00'),
(7, 47, '2026-12-12 14:35:00'),
(62, 97, '2026-01-20 16:50:00'),
(16, 39, '2026-02-15 10:25:00'),
(96, 74, '2026-03-10 14:15:00'),
(32, 1, '2026-04-04 11:55:00'),
(87, 51, '2026-04-26 16:30:00'),
(49, 89, '2026-05-19 09:40:00'),
(1, 25, '2026-06-10 13:20:00'),
(77, 61, '2026-07-01 15:05:00'),
(59, 3, '2026-07-22 10:50:00'),
(24, 78, '2026-08-13 14:10:00'),
(90, 46, '2026-09-03 11:35:00'),
(35, 12, '2026-09-24 16:25:00'),
(12, 54, '2026-10-15 09:15:00'), -- Par 12 e 54 (Ocorrência 8)
(69, 58, '2026-11-05 13:50:00'),
(45, 9, '2026-11-26 10:30:00'),
(20, 40, '2026-12-17 15:15:00'),
(100, 100, '2026-12-28 11:00:00'),
(42, 87, '2026-12-31 16:45:00'); -- Par 42 e 87 (Ocorrência 8)

-- PEDIDO
INSERT INTO PEDIDO (ID_PEDIDO, NUM_PEDIDO, DATA_PEDIDO, VENDEDOR_ID_VENDEDOR, CLIENTE_ID_CLIENTE) VALUES
(1, 1, '2026-01-02 09:15:00', 1, 5),   -- Vendedor 1 e Cliente 5 (Ocorrência 1)
(2, 2, '2026-01-04 14:30:00', 2, 10),  -- Vendedor 2 e Cliente 10 (Ocorrência 1)
(3, 3, '2026-01-07 11:05:00', 3, 15),  -- Vendedor 3 e Cliente 15 (Ocorrência 1)
(4, 4, '2026-01-10 16:22:00', 1, 5),   -- Vendedor 1 e Cliente 5 (Ocorrência 2)
(5, 5, '2026-01-12 10:45:00', 5, 20),  -- Vendedor 5 e Cliente 20 (Ocorrência 1)
(6, 6, '2026-01-15 13:12:00', 2, 10),  -- Vendedor 2 e Cliente 10 (Ocorrência 2)
(7, 7, '2026-01-18 15:40:00', 7, 7),
(8, 8, '2026-01-20 09:00:00', 3, 15),  -- Vendedor 3 e Cliente 15 (Ocorrência 2)
(9, 9, '2026-01-23 11:55:00', 9, 12),
(10, 10, '2026-01-26 14:18:00', 5, 20), -- Vendedor 5 e Cliente 20 (Ocorrência 2)
(11, 11, '2026-01-29 16:50:00', 1, 5),  -- Vendedor 1 e Cliente 5 (Ocorrência 3)
(12, 12, '2026-02-01 10:25:00', 2, 10), -- Vendedor 2 e Cliente 10 (Ocorrência 3)
(13, 13, '2026-02-03 12:10:00', 3, 15), -- Vendedor 3 e Cliente 15 (Ocorrência 3)
(14, 14, '2026-02-06 15:35:00', 4, 2),
(15, 15, '2026-02-09 09:14:00', 5, 20), -- Vendedor 5 e Cliente 20 (Ocorrência 3)
(16, 16, '2026-02-11 11:20:00', 1, 5),  -- Vendedor 1 e Cliente 5 (Ocorrência 4)
(17, 17, '2026-02-14 14:45:00', 2, 10), -- Vendedor 2 e Cliente 10 (Ocorrência 4)
(18, 18, '2026-02-17 16:05:00', 8, 18),
(19, 19, '2026-02-20 10:00:00', 3, 15), -- Vendedor 3 e Cliente 15 (Ocorrência 4)
(20, 20, '2026-02-22 13:52:00', 5, 20), -- Vendedor 5 e Cliente 20 (Ocorrência 4)
(21, 21, '2026-02-25 15:15:00', 1, 5),  -- Vendedor 1 e Cliente 5 (Ocorrência 5)
(22, 22, '2026-02-28 09:30:00', 2, 10), -- Vendedor 2 e Cliente 10 (Ocorrência 5)
(23, 23, '2026-03-03 11:40:00', 3, 15), -- Vendedor 3 e Cliente 15 (Ocorrência 5)
(24, 24, '2026-03-05 14:12:00', 6, 14),
(25, 25, '2026-03-08 16:55:00', 5, 20), -- Vendedor 5 e Cliente 20 (Ocorrência 5)
(26, 26, '2026-03-11 10:20:00', 1, 5),  -- Vendedor 1 e Cliente 5 (Ocorrência 6)
(27, 27, '2026-03-14 13:45:00', 2, 10), -- Vendedor 2 e Cliente 10 (Ocorrência 6)
(28, 28, '2026-03-16 15:10:00', 3, 15), -- Vendedor 3 e Cliente 15 (Ocorrência 6)
(29, 29, '2026-03-19 09:25:00', 7, 8),
(30, 30, '2026-03-22 11:30:00', 5, 20), -- Vendedor 5 e Cliente 20 (Ocorrência 6)
(31, 31, '2026-03-25 14:05:00', 1, 5),  -- Vendedor 1 e Cliente 5 (Ocorrência 7)
(32, 32, '2026-03-27 16:40:00', 2, 10), -- Vendedor 2 e Cliente 10 (Ocorrência 7)
(33, 33, '2026-03-30 10:15:00', 3, 15), -- Vendedor 3 e Cliente 15 (Ocorrência 7)
(34, 34, '2026-04-02 12:50:00', 8, 19),
(35, 35, '2026-04-05 15:33:00', 5, 20), -- Vendedor 5 e Cliente 20 (Ocorrência 7)
(36, 36, '2026-04-08 09:05:00', 1, 5),  -- Vendedor 1 e Cliente 5 (Ocorrência 8)
(37, 37, '2026-04-10 11:42:00', 2, 10), -- Vendedor 2 e Cliente 10 (Ocorrência 8)
(38, 38, '2026-04-13 14:18:00', 3, 15), -- Vendedor 3 e Cliente 15 (Ocorrência 8)
(39, 39, '2026-04-16 16:55:00', 9, 3),
(40, 40, '2026-04-19 10:10:00', 5, 20), -- Vendedor 5 e Cliente 20 (Ocorrência 8)
(41, 41, '2026-04-21 13:25:00', 4, 11), -- Vendedor 4 e Cliente 11 (Ocorrência 1)
(42, 42, '2026-04-24 15:50:00', 6, 16), -- Vendedor 6 e Cliente 16 (Ocorrência 1)
(43, 43, '2026-04-27 09:12:00', 4, 11), -- Vendedor 4 e Cliente 11 (Ocorrência 2)
(44, 44, '2026-04-30 11:30:00', 10, 1),
(45, 45, '2026-05-02 14:40:00', 6, 16), -- Vendedor 6 e Cliente 16 (Ocorrência 2)
(46, 46, '2026-05-05 16:15:00', 4, 11), -- Vendedor 4 e Cliente 11 (Ocorrência 3)
(47, 47, '2026-05-08 10:05:00', 7, 13),
(48, 48, '2026-05-11 12:45:00', 6, 16), -- Vendedor 6 e Cliente 16 (Ocorrência 3)
(49, 49, '2026-05-13 15:20:00', 4, 11), -- Vendedor 4 e Cliente 11 (Ocorrência 4)
(50, 50, '2026-05-16 09:35:00', 8, 4),
(51, 51, '2026-05-19 11:10:00', 6, 16), -- Vendedor 6 e Cliente 16 (Ocorrência 4)
(52, 52, '2026-05-22 14:55:00', 4, 11), -- Vendedor 4 e Cliente 11 (Ocorrência 5)
(53, 53, '2026-05-24 16:30:00', 9, 6),
(54, 54, '2026-05-27 10:22:00', 6, 16), -- Vendedor 6 e Cliente 16 (Ocorrência 5)
(55, 55, '2026-05-30 13:14:00', 4, 11), -- Vendedor 4 e Cliente 11 (Ocorrência 6)
(56, 56, '2026-06-02 15:40:00', 10, 17),
(57, 57, '2026-06-05 09:18:00', 6, 16), -- Vendedor 6 e Cliente 16 (Ocorrência 6)
(58, 58, '2026-06-08 11:50:00', 4, 11), -- Vendedor 4 e Cliente 11 (Ocorrência 7)
(59, 59, '2026-06-10 14:11:00', 1, 9),
(60, 60, '2026-06-13 16:35:00', 6, 16), -- Vendedor 6 e Cliente 16 (Ocorrência 7)
(61, 61, '2026-06-16 10:00:00', 4, 11), -- Vendedor 4 e Cliente 11 (Ocorrência 8)
(62, 62, '2026-06-19 12:42:00', 2, 14),
(63, 63, '2026-06-22 15:15:00', 6, 16), -- Vendedor 6 e Cliente 16 (Ocorrência 8)
(64, 64, '2026-06-25 09:30:00', 7, 3),   -- Vendedor 7 e Cliente 3 (Ocorrência 1)
(65, 65, '2026-06-27 11:05:00', 8, 11),  -- Vendedor 8 e Cliente 11 (Ocorrência 1)
(66, 66, '2026-06-30 14:50:00', 7, 3),   -- Vendedor 7 e Cliente 3 (Ocorrência 2)
(67, 67, '2026-07-03 16:22:00', 9, 18),
(68, 68, '2026-07-06 10:14:00', 8, 11),  -- Vendedor 8 e Cliente 11 (Ocorrência 2)
(69, 69, '2026-07-09 13:35:00', 7, 3),   -- Vendedor 7 e Cliente 3 (Ocorrência 3)
(70, 70, '2026-07-12 15:58:00', 10, 6),
(71, 71, '2026-07-15 09:20:00', 8, 11),  -- Vendedor 8 e Cliente 11 (Ocorrência 3)
(72, 72, '2026-07-18 11:45:00', 7, 3),   -- Vendedor 7 e Cliente 3 (Ocorrência 4)
(73, 73, '2026-07-21 14:12:00', 1, 13),
(74, 74, '2026-07-24 16:30:00', 8, 11),  -- Vendedor 8 e Cliente 11 (Ocorrência 4)
(75, 75, '2026-07-27 10:05:00', 7, 3),   -- Vendedor 7 e Cliente 3 (Ocorrência 5)
(76, 76, '2026-07-30 12:55:00', 2, 19),
(77, 77, '2026-08-02 15:40:00', 8, 11),  -- Vendedor 8 e Cliente 11 (Ocorrência 5)
(78, 78, '2026-08-05 09:15:00', 7, 3),   -- Vendedor 7 e Cliente 3 (Ocorrência 6)
(79, 79, '2026-08-08 11:38:00', 3, 2),
(80, 80, '2026-08-11 14:22:00', 8, 11),  -- Vendedor 8 e Cliente 11 (Ocorrência 6)
(81, 81, '2026-08-14 16:50:00', 7, 3),   -- Vendedor 7 e Cliente 3 (Ocorrência 7)
(82, 82, '2026-08-17 10:10:00', 4, 15),
(83, 83, '2026-08-20 13:45:00', 8, 11),  -- Vendedor 8 e Cliente 11 (Ocorrência 7)
(84, 84, '2026-08-23 15:12:00', 7, 3),   -- Vendedor 7 e Cliente 3 (Ocorrência 8)
(85, 85, '2026-08-26 09:30:00', 5, 8),
(86, 86, '2026-08-29 11:55:00', 8, 11),  -- Vendedor 8 e Cliente 11 (Ocorrência 8)
(87, 87, '2026-09-01 14:20:00', 9, 10), -- Vendedor 9 e Cliente 10 (Ocorrência 1)
(88, 88, '2026-09-04 16:45:00', 10, 14),-- Vendedor 10 e Cliente 14 (Ocorrência 1)
(89, 89, '2026-09-07 10:02:00', 9, 10), -- Vendedor 9 e Cliente 10 (Ocorrência 2)
(90, 90, '2026-09-10 12:35:00', 10, 14),-- Vendedor 10 e Cliente 14 (Ocorrência 2)
(91, 91, '2026-09-13 15:18:00', 9, 10), -- Vendedor 9 e Cliente 10 (Ocorrência 3)
(92, 92, '2026-09-16 09:40:00', 10, 14),-- Vendedor 10 e Cliente 14 (Ocorrência 3)
(93, 93, '2026-09-19 11:15:00', 9, 10), -- Vendedor 9 e Cliente 10 (Ocorrência 4)
(94, 94, '2026-09-22 14:50:00', 10, 14),-- Vendedor 10 e Cliente 14 (Ocorrência 4)
(95, 95, '2026-09-25 16:22:00', 9, 10), -- Vendedor 9 e Cliente 10 (Ocorrência 5)
(96, 96, '2026-09-28 10:05:00', 10, 14),-- Vendedor 10 e Cliente 14 (Ocorrência 5)
(97, 97, '2026-10-01 13:30:00', 9, 10), -- Vendedor 9 e Cliente 10 (Ocorrência 6)
(98, 98, '2026-10-01 14:10:00', 10, 14),-- Vendedor 10 e Cliente 14 (Ocorrência 6)
(99, 99, '2026-10-01 15:55:00', 9, 10), -- Vendedor 9 e Cliente 10 (Ocorrência 7)
(100, 100, '2026-10-01 16:45:00', 10, 14);-- Vendedor 10 e Cliente 14 (Ocorrência 7)

-- PRODUTO
INSERT INTO PRODUTO (ID_PRODUTO, NOME_PRODUTO, DESCRICAO_PRODUTO, PART_NUMBER_PRODUTO, PU_PRODUTO, QUANT_PRODUTO, UNIDADE_FORNECIMENTO_PRODUTO, DATA_FABRIC_PRODUTO, DATA_VALIDADE_PRODUTO, COD_BARRA_PRODUTO) VALUES
(1, 'Bola de Futebol Campo', 'Bola oficial de couro sintético tamanho 5', 1001, 149.90, 50, 'UN', '2026-01-10 08:00:00', '2031-01-10', '7891001000012'),
(2, 'Chuteira Society Couro', 'Chuteira com travas baixas para grama sintética', 1002, 299.99, 30, 'PAR', '2026-01-15 09:30:00', '2031-01-15', '7891001000029'),
(3, 'Camisa Térmica Manga Longa', 'Camisa de compressão com proteção UV50+', 1003, 89.90, 120, 'UN', '2026-02-01 14:15:00', '2036-02-01', '7891001000036'),
(4, 'Meião de Futebol Profissional', 'Meião com elastano e sola atoalhada', 1004, 25.00, 200, 'PAR', '2025-12-10 11:00:00', '2035-12-10', '7891001000043'),
(5, 'Luva de Goleiro Latex', 'Luva com grip profissional para campo', 1005, 189.50, 25, 'PAR', '2026-01-20 10:45:00', '2031-01-20', '7891001000050'),
(6, 'Caneleira de Impacto leve', 'Caneleira com proteção em EVA interna', 1006, 39.90, 80, 'UN', '2026-02-10 16:20:00', '2036-02-10', '7891001000067'),
(7, 'Rede de Futebol Trave Campo', 'Par de redes tipo colmeia fio 4mm', 1007, 349.00, 10, 'JG', '2025-11-05 08:30:00', '2035-11-05', '7891001000074'),
(8, 'Bomba de Inflar Bolas', 'Bomba manual com bico de metal incluso', 1008, 45.00, 65, 'UN', '2026-01-05 13:00:00', '2036-01-05', '7891001000081'),
(9, 'Cartão de Árbitro Kit', 'Conjunto com cartão amarelo, vermelho e bloco', 1009, 19.90, 40, 'KT', '2025-09-15 09:00:00', '2035-09-15', '7891001000098'),
(10, 'Cronômetro Digital Profissional', 'Cronômetro com memória de 10 voltas', 1010, 119.90, 35, 'UN', '2026-02-18 10:00:00', '2031-02-18', '7891001000104'),
(11, 'Bola de Basquete Tam 7', 'Bola de borracha vulcanizada para outdoor', 1011, 129.90, 45, 'UN', '2026-01-22 15:30:00', '2031-01-22', '7891001000111'),
(12, 'Aro de Basquete com Molas', 'Aro oficial retrátil com rede de nylon', 1012, 450.00, 8, 'UN', '2025-10-25 14:00:00', '2035-10-25', '7891001000128'),
(13, 'Rede de Basquete Anti-Chicotada', 'Rede de nylon fio 6mm resistente ao tempo', 1013, 35.00, 90, 'UN', '2026-01-12 11:15:00', '2036-01-12', '7891001000135'),
(14, 'Tênis de Basquete Cano Alto', 'Tênis com amortecimento em gel reforçado', 1014, 599.90, 22, 'PAR', '2026-03-01 08:45:00', '2031-03-01', '7891001000142'),
(15, 'Bermuda de Basquete Mesh', 'Bermuda larga ventilada com bolsos', 1015, 79.90, 110, 'UN', '2026-02-20 16:10:00', '2036-02-20', '7891001000159'),
(16, 'Placar Eletrônico de Mesa', 'Placar digital com controle remoto', 1016, 899.00, 5, 'UN', '2026-01-30 09:20:00', '2031-01-30', '7891001000166'),
(17, 'Fita de Demarcação Quadra', 'Rolo de fita adesiva de alta aderência 50mm', 1017, 49.90, 70, 'RL', '2025-08-14 13:40:00', '2030-08-14', '7891001000173'),
(18, 'Bola de Vôlei de Praia', 'Bola de couro macio costurada à mão', 1018, 159.00, 38, 'UN', '2026-02-05 11:25:00', '2031-02-05', '7891001000180'),
(19, 'Rede de Vôlei 4 Faixas', 'Rede oficial com cabo de aço interno', 1019, 280.00, 12, 'UN', '2025-12-22 10:15:00', '2035-12-22', '7891001000197'),
(20, 'Antena de Vôlei Oficial', 'Par de antenas de fibra de vidro com capa', 1020, 110.00, 15, 'PAR', '2025-07-19 15:50:00', '2035-07-19', '7891001000203'),
(21, 'Joelheira de Vôlei Elástica', 'Joelheira com proteção de espuma expandida', 1021, 65.00, 85, 'PAR', '2026-01-14 14:30:00', '2036-01-14', '7891001000210'),
(22, 'Manguito de Compressão Vôlei', 'Manguito protetor para amortecer impacto', 1022, 34.90, 140, 'PAR', '2026-03-05 09:10:00', '2036-03-05', '7891001000227'),
(23, 'Bola de Handebol Masc H3', 'Bola com ótima aderência para cola', 1023, 139.90, 25, 'UN', '2026-02-11 11:35:00', '2031-02-11', '7891001000234'),
(24, 'Bola de Handebol Fem H2', 'Bola oficial feminina tamanho reduzido', 1024, 139.90, 20, 'UN', '2026-02-11 11:40:00', '2031-02-11', '7891001000241'),
(25, 'Resina para Handebol Cola', 'Pote de resina natural 500g para grip', 1025, 75.00, 40, 'UN', '2026-01-18 16:00:00', '2028-01-18', '7891001000258'),
(26, 'Raquete de Tênis Grafite', 'Raquete leve de performance equilíbrio médio', 1026, 749.00, 14, 'UN', '2026-02-25 10:20:00', '2036-02-25', '7891001000265'),
(27, 'Tubo de Bola de Tênis c/ 3', 'Bolas pressurizadas de alta durabilidade', 1027, 39.90, 180, 'CX', '2026-03-10 08:15:00', '2027-09-10', '7891001000272'),
(28, 'Overgrip para Raquete Absorvente', 'Fita emborrachada para cabo de raquete', 1028, 15.00, 300, 'UN', '2026-01-08 14:50:00', '2036-01-08', '7891001000289'),
(29, 'Rede de Tênis Saibro/Fita', 'Rede oficial com lona superior de lona', 1029, 399.00, 6, 'UN', '2025-10-12 11:30:00', '2035-10-12', '7891001000296'),
(30, 'Raquete de Beach Tennis Carbono', 'Raquete face texturizada furos otimizados', 1030, 499.00, 28, 'UN', '2026-02-14 13:00:00', '2036-02-14', '7891001000302'),
(31, 'Bola de Beach Tennis Estágio 2', 'Pack com 3 bolas de baixa pressão', 1031, 34.90, 150, 'CX', '2026-01-28 15:45:00', '2028-07-28', '7891001000319'),
(32, 'Raquete de Ping Pong Clássica', 'Raquete de madeira com borracha dos dois lados', 1032, 59.90, 50, 'UN', '2025-11-20 09:10:00', '2035-11-20', '7891001000326'),
(33, 'Bolinha de Ping Pong 3 Estrelas', 'Caixa com 6 unidades de celuloide 40mm', 1033, 24.90, 130, 'CX', '2026-01-09 10:00:00', '2036-01-09', '7891001000333'),
(34, 'Rede de Ping Pong Retrátil', 'Rede com suportes tipo mola clipe rápido', 1034, 49.00, 45, 'UN', '2025-12-05 14:25:00', '2035-12-05', '7891001000340'),
(35, 'Óculos de Natação Antiembaçante', 'Lentes com proteção UV tira de silicone', 1035, 79.90, 95, 'UN', '2026-01-19 11:20:00', '2031-01-19', '7891001000357'),
(36, 'Touca de Natação Silicone', 'Touca impermeável de alta elasticidade', 1036, 25.00, 250, 'UN', '2026-02-04 08:35:00', '2036-02-04', '7891001000364'),
(37, 'Prancha de Natação EVA', 'Prancha para treino de pernas grande', 1037, 45.00, 40, 'UN', '2026-01-11 13:50:00', '2036-01-11', '7891001000371'),
(38, 'Palmar para Natação Treino', 'Par de palmares ergonômicos ajustáveis', 1038, 69.90, 30, 'PAR', '2025-10-30 15:00:00', '2035-10-30', '7891001000388'),
(39, 'Protetor Auricular Silicone', 'Par de protetores moldáveis para ouvido', 1039, 15.00, 180, 'PAR', '2026-02-15 09:40:00', '2036-02-15', '7891001000395'),
(40, 'Nervura/Clip Nasal Natação', 'Presilha nasal leve de policarbonato', 1040, 12.50, 120, 'UN', '2026-01-24 10:15:00', '2036-01-24', '7891001000401'),
(41, 'Toalha de Natação Secagem Rápida', 'Toalha de microfibra super absorvente M', 1041, 55.00, 85, 'UN', '2025-11-18 16:30:00', '2035-11-18', '7891001000418'),
(42, 'Tapete de Yoga Premium 6mm', 'Tapete antiderrapante em TPE ecológico', 1042, 139.90, 60, 'UN', '2026-02-02 08:10:00', '2036-02-02', '7891001000425'),
(43, 'Bloco de Yoga EVA', 'Bloco leve para apoio de posturas alongamento', 1043, 29.90, 100, 'UN', '2026-01-07 14:00:00', '2036-01-07', '7891001000432'),
(44, 'Cinta de Alongamento Yoga', 'Faixa de algodão com fivela ajustável', 1044, 24.90, 75, 'UN', '2025-09-03 11:20:00', '2035-09-03', '7891001000449'),
(45, 'Halter Emborrachado 2kg', 'Par de halteres de ferro com capa vinílica', 1045, 59.90, 50, 'PAR', '2025-12-15 10:00:00', '2035-12-15', '7891001000456'),
(46, 'Halter Emborrachado 5kg', 'Par de halteres pesados para musculação', 1046, 119.90, 35, 'PAR', '2025-12-15 10:30:00', '2035-12-15', '7891001000463'),
(47, 'Kettlebell de Ferro 8kg', 'Kettlebell pintado com alça anatômica', 1047, 145.00, 20, 'UN', '2025-11-04 15:45:00', '2035-11-04', '7891001000470'),
(48, 'Kettlebell de Ferro 12kg', 'Kettlebell funcional bruto para crossfit', 1048, 199.00, 15, 'UN', '2025-11-04 16:00:00', '2035-11-04', '7891001000487'),
(49, 'Faixa Elástica Mini Band Kit', 'Conjunto com 3 intensidades de elásticos', 1049, 45.00, 140, 'KT', '2026-02-28 09:50:00', '2036-02-28', '7891001000494'),
(50, 'Super Band Elástica Forte', 'Elástico extensor grosso para assistência', 1050, 79.90, 65, 'UN', '2026-02-28 10:15:00', '2036-02-28', '7891001000500'),
(51, 'Corda de Pular Rolamento', 'Corda de alta velocidade cabo de aço', 1051, 39.90, 110, 'UN', '2026-01-13 14:10:00', '2036-01-13', '7891001000517'),
(52, 'Roda Abdominal Dupla', 'Roda para treino de core com tapetinho', 1052, 59.90, 48, 'UN', '2026-02-09 11:00:00', '2036-02-09', '7891001000524'),
(53, 'Barra de Porta Ajustável', 'Barra extensível por pressão de 60 a 100cm', 1053, 99.90, 25, 'UN', '2025-10-18 13:20:00', '2035-10-18', '7891001000531'),
(54, 'Par de Tornozeleiras de Peso 3kg', 'Caneleiras de peso em nylon lavável', 1054, 75.00, 42, 'PAR', '2026-01-26 15:35:00', '2036-01-26', '7891001000548'),
(55, 'Luva de Musculação Neoprene', 'Par de luvas com palha antiderrapante', 1055, 34.90, 90, 'PAR', '2026-02-14 08:50:00', '2036-02-14', '7891001000555'),
(56, 'Cinto Lombar Academia', 'Cinto de couro com fivela dupla proteção', 1056, 129.00, 18, 'UN', '2025-08-27 16:10:00', '2035-08-27', '7891001000562'),
(57, 'Colchonete de Academia D23', 'Colchonete de espuma revestido em lona', 1057, 49.90, 55, 'UN', '2026-03-03 10:30:00', '2036-03-03', '7891001000579'),
(58, 'Grip de Crossfit Couro Lona', 'Protetor de palmas de mãos 3 furos', 1058, 65.00, 70, 'PAR', '2026-02-19 14:40:00', '2036-02-19', '7891001000586'),
(59, 'Fita de Suspensão Tipo TRX', 'Fita de treinamento suspenso regulável', 1059, 149.00, 22, 'UN', '2025-11-12 09:15:00', '2035-11-12', '7891001000593'),
(60, 'Bola de Pilates Suíça 65cm', 'Bola inflável anti-estouro com bomba', 1060, 89.90, 40, 'UN', '2026-01-29 11:05:00', '2031-01-29', '7891001000609'),
(61, 'Anel de Pilates Tonificador', 'Arco flexível com pegadores de espuma', 1061, 54.90, 30, 'UN', '2025-12-04 15:20:00', '2035-12-04', '7891001000616'),
(62, 'Disco de Equilíbrio Inflável', 'Disco propriocepção texturizado inflável', 1062, 69.90, 35, 'UN', '2026-01-06 13:45:00', '2036-01-06', '7891001000623'),
(63, 'Capacete de Ciclismo Mtb', 'Capacete com viseira removível e led traseiro', 1063, 159.90, 25, 'UN', '2026-02-22 09:00:00', '2031-02-22', '7891001000630'),
(64, 'Luva de Ciclismo Meio Dedo', 'Luva acolchoada com gel na palma', 1064, 45.00, 80, 'PAR', '2026-03-04 16:15:00', '2036-03-04', '7891001000647'),
(65, 'Bomba de Pé para Bicicleta', 'Bomba de chão com manômetro de pressão', 1065, 99.00, 20, 'UN', '2025-10-09 11:30:00', '2035-10-09', '7891001000654'),
(66, 'Garrafa Caramanhola Refletiva', 'Garrafa térmica 600ml para suporte bike', 1066, 39.90, 150, 'UN', '2026-02-15 14:10:00', '2031-02-15', '7891001000661'),
(67, 'Suporte de Caramanhola Nylon', 'Suporte leve para quadro de bicicleta', 1067, 19.90, 110, 'UN', '2025-09-11 08:50:00', '2035-09-11', '7891001000678'),
(68, 'Velocímetro de Bike sem Fio', 'Ciclocomputador wireless 15 funções', 1068, 129.90, 30, 'UN', '2026-01-17 10:25:00', '2031-01-17', '7891001000685'),
(69, 'Kit Remendo Pneu Bicicleta', 'Estojo com remendos, cola e lixa', 1069, 15.00, 200, 'KT', '2026-01-03 16:40:00', '2029-01-03', '7891001000692'),
(70, 'Lanterna Traseira Bike Led', 'Sinalizador recarregável USB à prova dágua', 1070, 34.90, 95, 'UN', '2026-02-10 13:00:00', '2031-02-10', '7891001000708'),
(71, 'Farol Dianteiro Bike Forte', 'Farol potente recarregável em alumínio', 1071, 119.00, 40, 'UN', '2026-02-10 13:15:00', '2031-10-10', '7891001000715'),
(72, 'Cadeado Trava de Bike Cabo U', 'Cadeado de aço com revestimento e chaves', 1072, 79.90, 50, 'UN', '2025-11-28 15:00:00', '2035-11-28', '7891001000722'),
(73, 'Pochete de Corrida Slim', 'Cinto porta celular impermeável elástico', 1073, 29.90, 130, 'UN', '2026-01-20 09:45:00', '2036-01-20', '7891001000739'),
(74, 'Meia de Compressão Corrida', 'Meia cano alto canelada performance', 1074, 49.90, 85, 'PAR', '2026-03-02 11:10:00', '2036-03-02', '7891001000746'),
(75, 'Viseira de Corrida Dry Fit', 'Viseira aba curva tecido respirável', 1075, 25.00, 100, 'UN', '2026-02-16 16:30:00', '2036-02-16', '7891001000753'),
(76, 'Óculos de Sol Esportivo Ciclismo', 'Óculos panorâmico proteção UVA/UVB', 1076, 149.90, 35, 'UN', '2026-01-24 14:50:00', '2031-01-24', '7891001000760'),
(77, 'Kimono de Jiu Jitsu Trançado', 'Kimono de algodão reforçado sem faixa', 1077, 320.00, 15, 'UN', '2025-12-05 10:10:00', '2035-12-05', '7891001000777'),
(78, 'Faixa Branca Artes Marciais', 'Faixa de algodão reforçada 2,80m', 1078, 25.00, 40, 'UN', '2025-11-15 08:30:00', '2035-11-15', '7891001000784'),
(79, 'Faixa Azul Artes Marciais', 'Faixa reforçada jiu-jitsu/judô', 1079, 25.00, 30, 'UN', '2025-11-15 08:45:00', '2035-11-15', '7891001000791'),
(80, 'Luva de Boxe Bate-Saco', 'Luva de PU acolchoamento grosso 12oz', 1080, 179.90, 20, 'PAR', '2026-01-14 11:20:00', '2031-01-14', '7891001000807'),
(81, 'Bandagem Elástica Boxe 3m', 'Par de bandagens de algodão com velcro', 1081, 29.90, 90, 'PAR', '2026-02-05 15:40:00', '2036-02-05', '7891001000821'),
(82, 'Protetor Bucal Moldável', 'Protetor de silicone termomoldável simples', 1082, 15.00, 150, 'UN', '2026-01-10 09:15:00', '2036-01-10', '7891001000838'),
(83, 'Saco de Pancadas Profissional', 'Saco de pancadas vazio lona sintética 1mt', 1083, 199.00, 12, 'UN', '2025-10-22 13:45:00', '2035-10-22', '7891001000845'),
(84, 'Corda de Agilidade Funcional', 'Escada de agilidade treino de chão 4m', 1084, 49.90, 35, 'UN', '2025-09-30 11:00:00', '2035-09-30', '7891001000852'),
(85, 'Cone de Sinalização Prato', 'Kit com 10 pratinhos demarcatórios flexíveis', 1085, 35.00, 80, 'KT', '2025-08-12 14:15:00', '2035-08-12', '7891001000869'),
(86, 'Baralho de Cartas de Treino', 'Cartas plastificadas com rotinas WOD', 1086, 24.90, 60, 'UN', '2025-07-20 16:00:00', '2035-07-20', '7891001000876'),
(87, 'Tapete de Dança / Step Eva', 'Plataforma rígida de step funcional', 1087, 89.90, 25, 'UN', '2025-11-03 10:45:00', '2035-11-03', '7891001000883'),
(88, 'Mesa de Pebolim Completa', 'Mesa de madeira com ferros embutidos', 1088, 1299.00, 3, 'UN', '2025-06-18 15:30:00', '2035-06-18', '7891001000890'),
(89, 'Bola de Pebolim Unidade', 'Bolinha plástica frisada reposição', 1089, 5.00, 200, 'UN', '2026-01-11 09:00:00', '2036-01-11', '7891001000906'),
(90, 'Alvo de Dardos Eletrônico', 'Painel automático com 6 dardos ponta plástico', 1090, 249.90, 10, 'UN', '2025-12-14 14:00:00', '2030-12-14', '7891001000913'),
(91, 'Dardos Profissionais Kit', 'Conjunto reposição com 3 dardos metal', 1091, 45.00, 50, 'KT', '2025-09-08 10:25:00', '2035-09-08', '7891001000920'),
(92, 'Rede de Basquete Corrente', 'Rede de metal com elos de aço galvanizado', 1092, 110.00, 15, 'UN', '2025-10-02 11:45:00', '2035-10-02', '7891001000937'),
(93, 'Medidor de Pressão Bolas', 'Calibrador de ponteiro em metal de bolso', 1093, 59.90, 25, 'UN', '2025-11-11 08:35:00', '2035-11-11', '7891001000944'),
(94, 'Prancha de Surf Softboard', 'Prancha iniciante revestida em espuma macia', 1094, 899.00, 6, 'UN', '2025-10-20 13:10:00', '2030-10-20', '7891001000951'),
(95, 'Leash para Prancha Surf', 'Corda de segurança tornozelo poliuretano', 1095, 75.00, 30, 'UN', '2026-01-08 16:20:00', '2036-01-08', '7891001000968'),
(96, 'Parafina para Prancha Agua Quente', 'Barra de parafina antiderrapante 80g', 1096, 12.00, 180, 'UN', '2026-02-14 09:30:00', '2027-02-14', '7891001000975'),
(97, 'Skate Street Completo', 'Shape de marfim trucks de liga e rodas 52mm', 1097, 249.00, 18, 'UN', '2026-01-19 14:50:00', '2036-01-19', '7891001000982'),
(98, 'Rolamento de Skate Red Bones', 'Jogo com 8 rolamentos de alta precisão', 1098, 119.90, 45, 'JG', '2025-12-03 10:15:00', '2035-12-03', '7891001000999'),
(99, 'Rodinhas de Skate Poliuretano', 'Jogo com 4 rodas dureza 99a tamanho 54mm', 1099, 89.90, 32, 'JG', '2025-11-21 15:40:00', '2035-11-21', '7891001001002'),
(100, 'Coifa Protetora Skatista Kit', 'Kit com joelheiras, cotoveleiras e capacete', 1100, 179.90, 20, 'KT', '2025-12-10 11:20:00', '2035-12-10', '7891001001019');

-- PEDIDO-PRODUTO
INSERT INTO ITEM_PEDIDO (PEDIDO_ID_PEDIDO, PRODUTO_ID_PRODUTO, QUANT_ITEM_PEDIDO) VALUES
(1, 4, 7), (1, 95, 6),
(2, 18, 4), (2, 14, 9), (2, 95, 3),
(3, 12, 6), (3, 28, 3),
(4, 90, 9), (4, 92, 6), (4, 84, 10),
(5, 1, 9), (5, 98, 8), (5, 21, 7),
(6, 98, 4), (6, 28, 4), (6, 44, 9),
(7, 45, 7), (7, 46, 3),
(8, 16, 7), (8, 64, 4), (8, 32, 9), (8, 48, 5),
(9, 78, 9), (9, 39, 4),
(10, 48, 10), (10, 89, 7), (10, 82, 3), (10, 4, 10),
(11, 41, 10), (11, 42, 6),
(12, 92, 4), (12, 62, 5), (12, 50, 8),
(13, 10, 9), (13, 23, 7), (13, 24, 7),
(14, 85, 3), (14, 30, 4), (14, 23, 4),
(15, 36, 10), (15, 13, 4),
(16, 68, 6), (16, 5, 8), (16, 8, 9),
(17, 30, 8), (17, 52, 9), (17, 94, 8),
(18, 41, 4), (18, 11, 6), (18, 86, 3), (18, 89, 4),
(19, 7, 7), (19, 63, 6), (19, 87, 8),
(20, 64, 5), (20, 11, 7), (20, 15, 5), (20, 92, 8),
(21, 10, 5), (21, 91, 5), (21, 53, 9),
(22, 6, 8), (22, 44, 4), (22, 17, 8), (22, 53, 3),
(23, 85, 4), (23, 28, 5), (23, 76, 5),
(24, 98, 9), (24, 5, 5), (24, 39, 9),
(25, 48, 5), (25, 60, 4), (25, 93, 10),
(26, 42, 4), (26, 75, 4), (26, 26, 8), (26, 92, 5),
(27, 40, 8), (27, 76, 4), (27, 84, 8),
(28, 84, 9), (28, 2, 7), (28, 99, 4),
(29, 39, 3), (29, 74, 9),
(30, 71, 10), (30, 39, 4), (30, 8, 9), (30, 21, 5),
(31, 50, 4), (31, 23, 7), (31, 88, 3),
(32, 98, 10), (32, 38, 10), (32, 73, 5), (32, 21, 6),
(33, 49, 10), (33, 30, 7), (33, 94, 9),
(34, 1, 9), (34, 43, 6), (34, 18, 7), (34, 82, 3),
(35, 10, 8), (35, 94, 8), (35, 63, 6),
(36, 100, 3), (36, 12, 10), (36, 19, 7), (36, 91, 6),
(37, 70, 4), (37, 6, 4), (37, 30, 6),
(38, 99, 6), (38, 41, 6), (38, 11, 4), (38, 21, 9),
(39, 96, 4), (39, 68, 6), (39, 6, 3),
(40, 96, 6), (40, 43, 10), (40, 81, 7),
(41, 13, 6), (41, 78, 6),
(42, 67, 10), (42, 10, 8), (42, 52, 6), (42, 29, 7),
(43, 90, 8), (43, 67, 9), (43, 60, 4),
(44, 96, 7), (44, 13, 8), (44, 86, 6), (44, 63, 6),
(45, 96, 6), (45, 68, 10), (45, 78, 3),
(46, 33, 9), (46, 66, 6), (46, 6, 10),
(47, 97, 8), (47, 69, 5),
(48, 65, 8), (48, 98, 4), (48, 71, 9), (48, 52, 7),
(49, 90, 7), (49, 75, 4),
(50, 42, 7), (50, 11, 5), (50, 46, 10), (50, 84, 3),
(51, 10, 9), (51, 80, 5),
(52, 9, 3), (52, 85, 3), (52, 94, 3), (52, 62, 5),
(53, 56, 3), (53, 26, 7), (53, 83, 3),
(54, 35, 9), (54, 99, 4), (54, 5, 8), (54, 69, 3),
(55, 66, 7), (55, 36, 10),
(56, 13, 10), (56, 45, 9), (56, 79, 3), (56, 84, 8),
(57, 50, 3), (57, 23, 7), (57, 27, 4),
(58, 64, 4), (58, 6, 4), (58, 93, 3),
(59, 13, 7), (59, 14, 4),
(60, 32, 9), (60, 86, 8), (60, 56, 4), (60, 29, 6),
(61, 89, 7), (61, 91, 5), (61, 63, 6),
(62, 42, 6), (62, 79, 6), (62, 15, 6), (62, 31, 3),
(63, 71, 7), (63, 91, 7), (63, 28, 4),
(64, 99, 5), (64, 69, 5), (64, 15, 5), (64, 21, 6),
(65, 35, 5), (65, 45, 10),
(66, 64, 8), (66, 74, 9), (66, 21, 6), (66, 92, 10),
(67, 34, 10), (67, 39, 4), (67, 61, 5),
(68, 66, 3), (68, 43, 7), (68, 47, 8), (68, 23, 8),
(69, 65, 9), (69, 90, 8),
(70, 3, 5), (70, 71, 7), (70, 78, 10), (70, 48, 5),
(71, 73, 5), (71, 99, 8),
(72, 32, 8), (72, 70, 10), (72, 8, 3), (72, 27, 8),
(73, 1, 9), (73, 66, 10), (73, 60, 9),
(74, 96, 7), (74, 75, 4), (74, 12, 10), (74, 53, 5),
(75, 99, 4), (75, 43, 10), (75, 15, 3),
(76, 34, 7), (76, 99, 8), (76, 88, 5), (76, 25, 5),
(77, 10, 4), (77, 83, 3),
(78, 64, 10), (78, 97, 8), (78, 35, 9), (78, 68, 9),
(79, 13, 8), (79, 53, 7),
(80, 40, 7), (80, 14, 5), (80, 21, 5), (80, 54, 7),
(81, 66, 3), (81, 19, 5), (81, 87, 8),
(82, 33, 4), (82, 97, 3), (82, 69, 9), (82, 6, 7),
(83, 67, 3), (83, 5, 8),
(84, 99, 8), (84, 73, 6), (84, 82, 8), (84, 21, 6),
(85, 35, 9), (85, 61, 8),
(86, 32, 5), (86, 69, 7), (86, 42, 10), (86, 15, 7),
(87, 65, 4), (87, 43, 4),
(88, 97, 5), (88, 68, 8), (88, 50, 4), (88, 25, 4),
(89, 98, 9), (89, 23, 7),
(90, 64, 10), (90, 34, 3), (90, 11, 4), (90, 76, 8),
(91, 10, 8), (91, 31, 3),
(92, 40, 9), (92, 73, 3), (92, 19, 7), (92, 85, 9),
(93, 32, 9), (93, 1, 3), (93, 35, 3),
(94, 69, 8), (94, 73, 9), (94, 15, 3),
(95, 34, 7), (95, 13, 7), (95, 54, 8),
(96, 68, 6), (96, 12, 10), (96, 36, 9),
(97, 64, 5), (97, 42, 10), (97, 4, 6),
(98, 34, 7), (98, 44, 3), (98, 77, 6), (98, 36, 4),
(99, 6, 8), (99, 61, 4), (99, 71, 9),
(100, 14, 5), (100, 48, 6), (100, 52, 9);

SELECT
    VENDEDOR.NOME_VENDEDOR,
    VENDEDOR_ID_VENDEDOR,
    CLIENTE_ID_CLIENTE,
    CLIENTE.NOME_CLIENTE,
    DATE_FORMAT(VENDEDOR_CLIENTE.DATA_HORA_ATENDIMENTO, '%d')
    FROM VENDEDOR
    JOIN VENDEDOR_CLIENTE
    ON VENDEDOR.ID_VENDEDOR = VENDEDOR_CLIENTE.VENDEDOR_ID_VENDEDOR
    JOIN CLIENTE
    ON CLIENTE.ID_CLIENTE = VENDEDOR_CLIENTE.VENDEDOR_ID_VENDEDOR
    WHERE VENDEDOR.NOME_VENDEDOR LIKE '%Maria Soares%'
    ORDER BY VENDEDOR.ID_VENDEDOR ASC;