/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.tv.telas;

import com.mycompany.tv.midia.Filme;
import com.mycompany.tv.midia.Multimidia;
import com.mycompany.tv.midia.Serie;
import java.util.ArrayList;
import javax.swing.JOptionPane;

/**
 *
 * @author jefferson.rodrigues
 */
public class Home extends javax.swing.JFrame {

    private static ArrayList<Multimidia> lista;

    private static int pos = 0;

    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(Home.class.getName());

    /**
     * Creates new form Home
     */
    public Home() {
        initComponents();
        exibir();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lbMultimidia = new javax.swing.JLabel();
        btVoltar = new javax.swing.JButton();
        btAvancar = new javax.swing.JButton();
        BtAssistir = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        lbMultimidia.setText("...");

        btVoltar.setText("Voltar");
        btVoltar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btVoltarActionPerformed(evt);
            }
        });

        btAvancar.setText("Avançar");
        btAvancar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btAvancarActionPerformed(evt);
            }
        });

        BtAssistir.setText("Aguarde...");
        BtAssistir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtAssistirActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(btVoltar)
                        .addGap(18, 18, 18)
                        .addComponent(btAvancar)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(BtAssistir, javax.swing.GroupLayout.PREFERRED_SIZE, 143, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(lbMultimidia, javax.swing.GroupLayout.PREFERRED_SIZE, 366, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(16, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lbMultimidia, javax.swing.GroupLayout.PREFERRED_SIZE, 194, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btAvancar)
                    .addComponent(btVoltar)
                    .addComponent(BtAssistir))
                .addContainerGap(71, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btVoltarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btVoltarActionPerformed
        if (pos > 0) {
            pos--;
        }
        exibir();
    }//GEN-LAST:event_btVoltarActionPerformed

    private void btAvancarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btAvancarActionPerformed
        if (pos < lista.size() - 1) {
            pos++;
        }
        exibir();
    }//GEN-LAST:event_btAvancarActionPerformed

    private void BtAssistirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtAssistirActionPerformed
        Multimidia m = lista.get(Home.pos);

        switch (m) {
            case Filme f ->
                JOptionPane.showMessageDialog(rootPane, "Assistindo o filme " + f.getTitulo()
                        + "\n de duração " + f.getDuracao());
            case Serie s ->
                JOptionPane.showMessageDialog(rootPane, "Assistindo o capítulo 1/"
                        + s.getQtEpisodios()
                        + " da temporada 1/" + s.getQtTemporadas()
                        + "\nda série " + s.getTitulo());
            default -> {
            }
        }
    }//GEN-LAST:event_BtAssistirActionPerformed

    private void exibir() {
        Multimidia m = lista.get(Home.pos);
        String texto = "<html>";
        texto += "<p><b>" + m.getClass().getSimpleName() + "</b></p>";
        texto += m.toString().replaceAll("\n", "<br>");
        texto += "</html>";
        lbMultimidia.setText(texto);

        if (m instanceof Filme) {
            BtAssistir.setText("Assistir do Início");
        } else if (m instanceof Serie) {
            BtAssistir.setText("Assistir S1E1");
        }
    }

    public static void run(ArrayList<Multimidia> lista) {
        Home.lista = lista;
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new Home().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BtAssistir;
    private javax.swing.JButton btAvancar;
    private javax.swing.JButton btVoltar;
    private javax.swing.JLabel lbMultimidia;
    // End of variables declaration//GEN-END:variables
}
